<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>CitizensPortal.HttpApi.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.MultiTenancy" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.Autofac" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Serilog" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.Swashbuckle" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.Account.Web.OpenIddict" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.Emailing" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.MailKit" Version="8.3.0" />
    <PackageReference Include="Volo.Abp.BlobStoring.FileSystem" Version="8.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CitizensPortal.HttpApi\CitizensPortal.HttpApi.csproj" />
    <ProjectReference Include="..\CitizensPortal.Application\CitizensPortal.Application.csproj" />
    <ProjectReference Include="..\CitizensPortal.EntityFrameworkCore\CitizensPortal.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
